const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.NoSave,
		C3.Behaviors.Persist,
		C3.Behaviors.Timer,
		C3.Plugins.TiledBg,
		C3.Behaviors.Pin,
		C3.Behaviors.Rotate,
		C3.Behaviors.Tween,
		C3.Plugins.Spritefont2,
		C3.Behaviors.bound,
		C3.Behaviors.Anchor,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.Bullet,
		C3.Behaviors.MoveTo,
		C3.Plugins.Audio,
		C3.Plugins.Clipboard,
		C3.Plugins.NinePatch,
		C3.Plugins.Particles,
		C3.Behaviors.Orbit,
		C3.Behaviors.LOS,
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.List,
		C3.Plugins.filechooser,
		C3.Plugins.FileSystem,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Turret,
		C3.Plugins.Json,
		C3.Plugins.TextBox,
		C3.Plugins.Browser,
		C3.Behaviors.Fade,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Exps.UID,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.LocalStorage.Cnds.OnAllKeyNamesLoaded,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.LocalStorage.Exps.KeyCount,
		C3.Plugins.System.Exps.find,
		C3.Plugins.LocalStorage.Exps.KeyAt,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Exps.AsJSON,
		C3.Plugins.Arr.Cnds.CompareInstanceVar,
		C3.Plugins.LocalStorage.Acts.GetAllKeyNames,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.LocalStorage.Cnds.OnAnyItemGet,
		C3.Plugins.LocalStorage.Exps.Key,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.LoadFromJsonString,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.System.Exps.len,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Arr.Acts.SetInstanceVar,
		C3.Plugins.LocalStorage.Cnds.IsProcessingSets,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.System.Acts.SortZOrderByInstVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Spritefont2.Acts.SetX,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.LayerNumber,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Spritefont2.Cnds.PickDistance,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.Mouse.Cnds.OnRelease,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Behaviors.Timer.Exps.TotalTime,
		C3.Behaviors.Timer.Exps.Duration,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Arr.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.IsEffectEnabled,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Behaviors.EightDir.Acts.SetMaxSpeed,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.Orbit.Acts.Pin,
		C3.Behaviors.Orbit.Acts.SetRotation,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Exps.ObjectTypeName,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgba255,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Cnds.Repeat,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Acts.RotateTowardPosition,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Behaviors.EightDir.Acts.SetDefaultControls,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.EightDir.Exps.VectorX,
		C3.Plugins.Sprite.Cnds.CompareFrameTag,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Acts.Destroy,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Bullet.Exps.AngleOfMotion,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Exps.min,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Bullet.Acts.SetAcceleration,
		C3.Plugins.System.Cnds.PickOverlappingPoint,
		C3.Plugins.System.Cnds.PickByHighestLowestValue,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Behaviors.Orbit.Acts.SetSpeed,
		C3.Behaviors.Orbit.Exps.Speed,
		C3.Behaviors.Orbit.Acts.SetRadius,
		C3.Behaviors.Orbit.Exps.PrimaryRadius,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Behaviors.Orbit.Exps.SecondaryRadius,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.List.Acts.Remove,
		C3.Plugins.Arr.Exps.IndexOf,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Behaviors.EightDir.Exps.VectorY,
		C3.Behaviors.Orbit.Acts.SetOffsetAngle,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Pin.Acts.PinByDistance,
		C3.Behaviors.Pin.Acts.SetPinDistance,
		C3.Plugins.TiledBg.Acts.ZMoveToObject,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.TiledBg.Exps.UID,
		C3.Plugins.TiledBg.Acts.SetTowardPosition,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.TiledBg.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Cnds.HasChildren,
		C3.Plugins.List.Exps.ItemCount,
		C3.Plugins.List.Acts.AddItem,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.List.Exps.ItemTextAt,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.System.Exps.rgbex255,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.TiledBg.Acts.SetPosToObject,
		C3.Plugins.TiledBg.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.AnimationFrameTag,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Sprite.Cnds.IsCollisionEnabled,
		C3.Behaviors.MoveTo.Exps.MaxSpeed,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.RotateTowardAngle,
		C3.Behaviors.Tween.Cnds.OnAnyTweensFinished,
		C3.Behaviors.Turret.Acts.AddTarget,
		C3.Behaviors.Turret.Cnds.OnShoot,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Orbit.Acts.Unpin,
		C3.Behaviors.Orbit.Acts.SetEnabled,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.EightDir.Acts.SetDeceleration,
		C3.Behaviors.EightDir.Exps.Deceleration,
		C3.Behaviors.EightDir.Acts.SetAcceleration,
		C3.Behaviors.EightDir.Exps.Acceleration,
		C3.Behaviors.Pin.Cnds.IsPinned,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.MoveTo.Acts.SetEnabled,
		C3.Behaviors.Fade.Cnds.OnFadeInEnd,
		C3.Plugins.NinePatch.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Spritefont2.Acts.SetAngle,
		C3.Plugins.List.Exps.Count,
		C3.Behaviors.MoveTo.Acts.SetSpeed,
		C3.Behaviors.MoveTo.Cnds.CompareSpeed,
		C3.Behaviors.Bullet.Cnds.IsEnabled,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Spritefont2.Cnds.OnCreated,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Particles.Cnds.OnCreated,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Behaviors.Timer.Exps.CurrentTime,
		C3.Behaviors.Timer.Acts.StopAllTimers,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Arr.Acts.SetXYZ,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.Clipboard.Acts.CopyText,
		C3.Plugins.System.Cnds.OnSaveComplete,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.System.Exps.savestatejson,
		C3.Plugins.Clipboard.Cnds.OnCopySuccess,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.ResetPersisted,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.TextBox.Acts.Destroy,
		C3.Plugins.System.Acts.LoadStateJSON,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Cnds.OnLoadComplete,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.TextBox.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.NinePatch.Cnds.OnCreated,
		C3.Plugins.NinePatch.Acts.MoveToTop,
		C3.Plugins.NinePatch.Acts.MoveToBottom,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Spritefont2.Cnds.IsVisible,
		C3.Plugins.System.Acts.ToggleBoolVar
	];
};
self.C3_JsPropNameTable = [
	{NoSave: 0},
	{craftButton: 0},
	{craftButton2: 0},
	{craftButton3: 0},
	{ID: 0},
	{type: 0},
	{craftingSlot: 0},
	{hotbarSlot2: 0},
	{needs: 0},
	{inventorySlot: 0},
	{Persist: 0},
	{inventorys: 0},
	{Timer: 0},
	{manaBarBack: 0},
	{manaBarBack2: 0},
	{map: 0},
	{placingCursor: 0},
	{selectionSlot: 0},
	{selector: 0},
	{selectorInv: 0},
	{testingInventorys: 0},
	{manaBar: 0},
	{manaBarBack3: 0},
	{healthBar: 0},
	{healthBarBack: 0},
	{bossBarBack: 0},
	{bossBarFront: 0},
	{bossBar: 0},
	{chestSlot: 0},
	{ammoVisibility: 0},
	{trash: 0},
	{offhandVisbility: 0},
	{craftMaxButton: 0},
	{z: 0},
	{shouldSort: 0},
	{hasShadow: 0},
	{shadowType: 0},
	{natural: 0},
	{hardness: 0},
	{craftingPage: 0},
	{craftingStations: 0},
	{torch: 0},
	{torchLight: 0},
	{Health: 0},
	{breakingTool: 0},
	{spawnID: 0},
	{AmountMin: 0},
	{AmountMax: 0},
	{Spread: 0},
	{damageSpawnWidth: 0},
	{name: 0},
	{Tree: 0},
	{locked: 0},
	{tempStorageData: 0},
	{chest: 0},
	{goTo: 0},
	{copyPos: 0},
	{caveEnterance: 0},
	{craftingStations2: 0},
	{torchLight2: 0},
	{Pin: 0},
	{playerLight: 0},
	{Tree2: 0},
	{plantLight: 0},
	{lifetime: 0},
	{pierce: 0},
	{destroyEffect: 0},
	{autoAim: 0},
	{damageType: 0},
	{damageDamage: 0},
	{projType: 0},
	{canDamage: 0},
	{knockBack: 0},
	{spark: 0},
	{thorn: 0},
	{thornBall: 0},
	{ankhBall: 0},
	{ankhBall2: 0},
	{woodenArrow: 0},
	{ankhBall3: 0},
	{cursedArrow: 0},
	{miniSprout: 0},
	{ironTippedArrow: 0},
	{bolt: 0},
	{slimeBull: 0},
	{leafBall: 0},
	{silverTippedArrow: 0},
	{playerIcicle: 0},
	{playerIcicle2: 0},
	{playerIcicle3: 0},
	{cursedHandProjectile: 0},
	{cursedBolt: 0},
	{leafBall2: 0},
	{quake: 0},
	{Rotate: 0},
	{curseExplosion: 0},
	{runeShot: 0},
	{curseExplosion2: 0},
	{hitsTotal: 0},
	{hitsLeft: 0},
	{delay: 0},
	{connectedID: 0},
	{spiritSword: 0},
	{coin: 0},
	{ankhBall4: 0},
	{wave: 0},
	{coralArrow: 0},
	{staticField: 0},
	{staticArrow: 0},
	{randStorInst: 0},
	{orbitBubble: 0},
	{bubble: 0},
	{seaFoamBall: 0},
	{seafoamPuddle: 0},
	{spiritShield: 0},
	{toothedShieldHitbox: 0},
	{fireTrail: 0},
	{playerIcicle4: 0},
	{flare: 0},
	{fieryArrow: 0},
	{miniMeteor: 0},
	{growTime: 0},
	{effect: 0},
	{yoyoDamage: 0},
	{waterbolt: 0},
	{typhoon: 0},
	{typeNum: 0},
	{flyingKnife: 0},
	{flyArrow: 0},
	{grubBull: 0},
	{bloodWave: 0},
	{miniCocoon: 0},
	{grubBullInfestation: 0},
	{throwingCocoon: 0},
	{grubBull2: 0},
	{flyOrbital: 0},
	{centipedeOrbital: 0},
	{windArrow: 0},
	{windArrow2: 0},
	{isReturning: 0},
	{hadesHatchet: 0},
	{coin2: 0},
	{lavaBullet: 0},
	{starShard: 0},
	{sakuraBullet: 0},
	{petal: 0},
	{playerIcicle5: 0},
	{windExplosion: 0},
	{cherrySplinterSpec: 0},
	{cherryShuriken: 0},
	{blisterBladeSpecial: 0},
	{cherryWave: 0},
	{index: 0},
	{bubbleRingSpawner: 0},
	{bulbField: 0},
	{centipedeSpawner: 0},
	{cherryShurikenSpawner: 0},
	{spiritBomb: 0},
	{spiritBall: 0},
	{spiritBall2: 0},
	{soulDagger: 0},
	{ghostSpawner: 0},
	{ghostOrbital: 0},
	{soulWave: 0},
	{epitomeSkull: 0},
	{soulExplosion: 0},
	{soulArrow: 0},
	{graveArrow: 0},
	{soulBall: 0},
	{soulBall2: 0},
	{spiritSpearWave: 0},
	{spiritSpearWave2: 0},
	{graveArrow2: 0},
	{hydraSpawner: 0},
	{hydraBullet: 0},
	{bloodExplosion: 0},
	{leafBall3: 0},
	{curseExplosion3: 0},
	{iceBall: 0},
	{iceJavelin: 0},
	{frostBowIcicle: 0},
	{blizzardZone: 0},
	{blizzardBull: 0},
	{petal2: 0},
	{staticField2: 0},
	{radBeam: 0},
	{nuclearArrow: 0},
	{radiationExplosion: 0},
	{radBall: 0},
	{radRocket: 0},
	{megaRadRocket: 0},
	{bloodExplosion2: 0},
	{radKnife: 0},
	{mutantArrow: 0},
	{coin3: 0},
	{skeletonHand: 0},
	{stagSpike: 0},
	{stagSpike2: 0},
	{stagSpike3: 0},
	{woodenSpinner: 0},
	{ironSpinner: 0},
	{fierySpinner: 0},
	{pumpkin: 0},
	{pumpkin2: 0},
	{pumpkin3: 0},
	{fireWave: 0},
	{namiBubble: 0},
	{moriLeaf: 0},
	{flyingKnife2: 0},
	{koriIcicle: 0},
	{fireworkArrow: 0},
	{fireworkExplosion: 0},
	{karmaShot: 0},
	{spiritBall3: 0},
	{laser: 0},
	{knot: 0},
	{spiritBall4: 0},
	{wukongPetStaff: 0},
	{wukongPetStaff2: 0},
	{tentacleSpearTyphoon: 0},
	{trident: 0},
	{squidJaveline: 0},
	{torrentBlast: 0},
	{torrentMegaBlast: 0},
	{shellArrow: 0},
	{jellyBall: 0},
	{staticField3: 0},
	{jellyShock: 0},
	{hollowCore: 0},
	{hollowBall: 0},
	{megaHollowCore: 0},
	{chasmCrusherBull: 0},
	{starfish: 0},
	{starfishSpawner: 0},
	{spiritWhale: 0},
	{spiritFish: 0},
	{play: 0},
	{db: 0},
	{axe: 0},
	{stabDistance: 0},
	{speed: 0},
	{dagger: 0},
	{pickaxe: 0},
	{shovel: 0},
	{swingDeg: 0},
	{swingSpeed: 0},
	{swingDelay: 0},
	{double: 0},
	{doubleSwing: 0},
	{storedID: 0},
	{sword: 0},
	{stickTime: 0},
	{shoot: 0},
	{standard: 0},
	{manaCost: 0},
	{wand: 0},
	{bow: 0},
	{summonWeight: 0},
	{AIType: 0},
	{AIActive: 0},
	{range: 0},
	{attackSpeed: 0},
	{moveSpeed: 0},
	{equipedID: 0},
	{woodChip: 0},
	{cryolite: 0},
	{anubisGuardianSpirit: 0},
	{tome: 0},
	{tome2: 0},
	{jellyPet: 0},
	{sunSpot: 0},
	{windSpirit: 0},
	{curseFlameSpawner: 0},
	{zombiePet: 0},
	{Tween: 0},
	{deathClawSpec: 0},
	{quark: 0},
	{bow2: 0},
	{vampireBat: 0},
	{throwWidth: 0},
	{ang: 0},
	{boomerang: 0},
	{boomerang2: 0},
	{wukongPet: 0},
	{Type: 0},
	{damage: 0},
	{defenseCounter: 0},
	{BoundToLayout: 0},
	{Anchor: 0},
	{description: 0},
	{islandName: 0},
	{label: 0},
	{label2: 0},
	{manaCounter: 0},
	{label4: 0},
	{selectionName: 0},
	{healthCounter: 0},
	{bossHealthCounter: 0},
	{message: 0},
	{label5: 0},
	{difficultyText: 0},
	{phaseReader: 0},
	{staticLabel: 0},
	{dropItem: 0},
	{hammer: 0},
	{spawn: 0},
	{spawnType: 0},
	{frequency: 0},
	{max: 0},
	{initialReps: 0},
	{waterType: 0},
	{enemiesSpawnerSpawner: 0},
	{helmet: 0},
	{Solid: 0},
	{island: 0},
	{islandSprites: 0},
	{islandSprites2: 0},
	{itemIcon: 0},
	{player2: 0},
	{player3: 0},
	{isSwimming: 0},
	{"8Direction": 0},
	{ScrollTo: 0},
	{dash: 0},
	{playerHitbox: 0},
	{shadow: 0},
	{spawner: 0},
	{TiledBackground2: 0},
	{TiledBackground3: 0},
	{example: 0},
	{darknessReqMin: 0},
	{darknessReqMax: 0},
	{chance: 0},
	{trueEnemySpawner: 0},
	{water: 0},
	{TiledBackground4: 0},
	{TiledBackground5: 0},
	{TiledBackground6: 0},
	{TiledBackground7: 0},
	{TiledBackground8: 0},
	{TiledBackground9: 0},
	{water2: 0},
	{meteorShadow: 0},
	{Delay: 0},
	{MoveTo: 0},
	{yoyo: 0},
	{TiledBackground10: 0},
	{TiledBackground11: 0},
	{collide: 0},
	{arrowShadow: 0},
	{TiledBackground12: 0},
	{Audio: 0},
	{bloodSlimeCrack: 0},
	{boat: 0},
	{buffIcon: 0},
	{cherryGuardianCrack: 0},
	{Clipboard: 0},
	{clouds: 0},
	{clouds2: 0},
	{setDark: 0},
	{darkness: 0},
	{deathText: 0},
	{deathText2: 0},
	{drownDamage: 0},
	{drowning: 0},
	{TiledBackground13: 0},
	{skeletonKingCrack: 0},
	{bubbles: 0},
	{effectController: 0},
	{fieryTotem: 0},
	{flyingKnifeSpawner: 0},
	{goldRingSpawner: 0},
	{goToEnterace: 0},
	{hadesCrack: 0},
	{Orbit: 0},
	{HadesShield: 0},
	{healingBlossom: 0},
	{healingCircle: 0},
	{healingCircle2: 0},
	{healTotem: 0},
	{icicle: 0},
	{icicleShower: 0},
	{hasSaved: 0},
	{hasTweened: 0},
	{importSave: 0},
	{TiledBackground14: 0},
	{icicle4: 0},
	{icicleBackBurn: 0},
	{icicleShower2: 0},
	{borealCrack: 0},
	{water3: 0},
	{TiledBackground15: 0},
	{discordLink: 0},
	{radRocketShot: 0},
	{radKnifeSpawner: 0},
	{importSave2: 0},
	{meltdownCrack: 0},
	{stagStaff: 0},
	{wendigooCrack: 0},
	{TiledBackground16: 0},
	{candleFireSpawner: 0},
	{dragonCrack: 0},
	{boomerangBase: 0},
	{wukongCrack: 0},
	{LanternLordCrack: 0},
	{healingCircle3: 0},
	{TiledBackground17: 0},
	{tridentVortexSpawner: 0},
	{waveSpawner: 0},
	{amalgamationCrack: 0},
	{TiledBackground18: 0},
	{health: 0},
	{contactDamage: 0},
	{hasContactDamage: 0},
	{AIInt1: 0},
	{AIInt2: 0},
	{AIInt3: 0},
	{AIInt4: 0},
	{isBody: 0},
	{storedDamage: 0},
	{isBoss: 0},
	{isHead: 0},
	{mummy: 0},
	{desertNado: 0},
	{mummyStorm: 0},
	{pharaohDash: 0},
	{pharaoh: 0},
	{mummy2: 0},
	{cursedMummy: 0},
	{trent: 0},
	{slime: 0},
	{woodling: 0},
	{cerebulbum: 0},
	{bulb: 0},
	{spider: 0},
	{worm: 0},
	{pig: 0},
	{woodlingWizard: 0},
	{bulb2: 0},
	{frostSlime: 0},
	{icicleConstruct: 0},
	{wormMovement: 0},
	{LineOfSight: 0},
	{cryoWormHead: 0},
	{id: 0},
	{parentalID: 0},
	{cryoWormBody: 0},
	{icePickHead: 0},
	{icePickBody: 0},
	{cursedMummy2: 0},
	{cursedMummy3: 0},
	{cursedSkull: 0},
	{fish: 0},
	{piranha: 0},
	{puffer: 0},
	{jellyFish: 0},
	{JellyDash: 0},
	{megaJelly: 0},
	{lavaSpire: 0},
	{emberling: 0},
	{redWizard: 0},
	{magmaKnight: 0},
	{grub: 0},
	{cocoon: 0},
	{fly: 0},
	{centipedeHead: 0},
	{centipedeBody: 0},
	{bloodSlime: 0},
	{maggotHead: 0},
	{maggotBody: 0},
	{marbleWarrior: 0},
	{marbleArcher: 0},
	{philosopher: 0},
	{monolith: 0},
	{grandMarbleWarrior: 0},
	{monoSlime: 0},
	{monoSlime2: 0},
	{hasRot: 0},
	{hades: 0},
	{quetzalcoatlHead: 0},
	{quetzalcoatlBody: 0},
	{enchantedSlime: 0},
	{stoneConstruct: 0},
	{cherryWoodling: 0},
	{cherryTrent: 0},
	{angered: 0},
	{cherryGuardian: 0},
	{ghoul: 0},
	{frankenstein: 0},
	{ghost: 0},
	{skeleton: 0},
	{skeletonLegs: 0},
	{skeleton2: 0},
	{trainingDummy: 0},
	{weaver: 0},
	{monolith2: 0},
	{skeletonKing: 0},
	{enchantedSlimeExt: 0},
	{frostedSlime: 0},
	{blizzard: 0},
	{permafrostPickHead: 0},
	{permafrostPickBody: 0},
	{boreal: 0},
	{toxicGhoul: 0},
	{wasteCrab: 0},
	{nuclearWormHead: 0},
	{nuclearWormBody: 0},
	{nuclearConstruct: 0},
	{meltdown: 0},
	{wendigoo: 0},
	{wendigoBrute: 0},
	{wendigoSentry: 0},
	{mummy3: 0},
	{angleInternal: 0},
	{samurai: 0},
	{lantern: 0},
	{ninja: 0},
	{umbrella: 0},
	{cyclops: 0},
	{spirit: 0},
	{storAngle: 0},
	{lanternLord: 0},
	{dragon: 0},
	{dragonBody: 0},
	{wukong: 0},
	{glowJelly: 0},
	{barnacle: 0},
	{length: 0},
	{eelHead: 0},
	{eelBody: 0},
	{hasMove: 0},
	{amalgamation: 0},
	{leviathanHead: 0},
	{leviathanBody: 0},
	{woodling2: 0},
	{storUID: 0},
	{linked: 0},
	{ancientWoodlingDrone: 0},
	{ancientWoodling: 0},
	{puffBat: 0},
	{ancientWoodlingPriest: 0},
	{AJAX: 0},
	{CraftingData: 0},
	{inventory: 0},
	{itemData: 0},
	{tableData: 0},
	{selected: 0},
	{chestStorage: 0},
	{islandData: 0},
	{effectArray: 0},
	{effects: 0},
	{FileChooser: 0},
	{FileSystem: 0},
	{gameState: 0},
	{"9patch": 0},
	{bigBloodBall: 0},
	{cherryRip: 0},
	{cerebulbumCrack: 0},
	{cherrySuriken: 0},
	{cherrySuriken2: 0},
	{coatlPortal: 0},
	{cryoball: 0},
	{cryoCore: 0},
	{cryoWormCrack: 0},
	{cursedSoul: 0},
	{dockingPoint: 0},
	{bone: 0},
	{emberBall: 0},
	{frostSlimeExt: 0},
	{ghostBall: 0},
	{gooBall: 0},
	{gooSpawn: 0},
	{gooSpawn2: 0},
	{hadesFireball: 0},
	{hadesFireball2: 0},
	{hadesFireball3: 0},
	{hadesFireball4: 0},
	{hadesFireball5: 0},
	{icicle2: 0},
	{icicle3: 0},
	{frostedSlimeExt: 0},
	{lanternFire: 0},
	{rot: 0},
	{lanternFire2: 0},
	{lanternFire3: 0},
	{lanternFire4: 0},
	{jadeWukong: 0},
	{slimeBall: 0},
	{slimeBall2: 0},
	{Mouse: 0},
	{Keyboard: 0},
	{sandball: 0},
	{pharoahBall: 0},
	{pharaohCoffin: 0},
	{shine: 0},
	{progress: 0},
	{trentBall: 0},
	{vinePoker: 0},
	{slimeExt: 0},
	{trashEmpty: 0},
	{Bullet: 0},
	{vineSpawner: 0},
	{vineSpawner2: 0},
	{miniBulb: 0},
	{slimeShot: 0},
	{returnDisabled: 0},
	{logo: 0},
	{LocalStorage: 0},
	{saveIcon: 0},
	{saveButton: 0},
	{magicCircle: 0},
	{waveGleam: 0},
	{hasCleared: 0},
	{totem: 0},
	{pyramidRaidSpawn: 0},
	{sandball2: 0},
	{indexTotal: 0},
	{shop: 0},
	{mapDottedLine: 0},
	{timerReload: 0},
	{sandball3: 0},
	{shock: 0},
	{lightning: 0},
	{pharoahBall2: 0},
	{jellyCrack: 0},
	{Particles: 0},
	{spawnRegion: 0},
	{temp: 0},
	{lavaPool: 0},
	{Sprite: 0},
	{lavaPoolSpawner: 0},
	{magmaBomb: 0},
	{lavaPool2: 0},
	{meteorSpawner: 0},
	{magmaBomb2: 0},
	{meteor: 0},
	{meteorBull: 0},
	{meteorSpawner2: 0},
	{magmaBomb3: 0},
	{meteor2: 0},
	{magmaKnightCrack: 0},
	{meteorShower: 0},
	{string: 0},
	{specialProgress: 0},
	{spitball: 0},
	{slimeExt2: 0},
	{smallBloodBall: 0},
	{marbleField: 0},
	{marbleFieldSpawner: 0},
	{marbleFieldHitbox: 0},
	{sandball4: 0},
	{Turret: 0},
	{marbleBow: 0},
	{marbleArcherArrow: 0},
	{philosopherRocketIcon: 0},
	{philosopherRocket: 0},
	{magmaBomb4: 0},
	{missleRain: 0},
	{sandball5: 0},
	{slimeExt3: 0},
	{slimeExt4: 0},
	{meteor3: 0},
	{meteorSpawner3: 0},
	{infernoRingSpawner: 0},
	{quetzalCoatlCrack: 0},
	{monolithCrack: 0},
	{teleportBeam: 0},
	{starBit: 0},
	{rad: 0},
	{orbitStone: 0},
	{mossOrbital: 0},
	{magmaBomb5: 0},
	{meteorSpawner4: 0},
	{sakuraExplosionSpawner: 0},
	{spiritFlame: 0},
	{JSON: 0},
	{sakuraSpearEffect: 0},
	{frankConnection: 0},
	{soul: 0},
	{webBall: 0},
	{skeletonKingSword: 0},
	{phase: 0},
	{skeletonKingSword2: 0},
	{skeletonKingFireball: 0},
	{skeletonKingFireball2: 0},
	{soulBow: 0},
	{arrayImportLoadFixer: 0},
	{arrayExportLoadFixer: 0},
	{TiledBackground: 0},
	{newGameConfirm: 0},
	{console: 0},
	{console2: 0},
	{spiritSteelField: 0},
	{icePatch: 0},
	{freezeRadius: 0},
	{iceFieldSpawner: 0},
	{skeletonKingFireball3: 0},
	{icicleStar: 0},
	{borealBack: 0},
	{borealEye: 0},
	{megaIcicle: 0},
	{megaIcicle2: 0},
	{iceRealm: 0},
	{iceEye: 0},
	{fireflies: 0},
	{icePatchBottom: 0},
	{icePatchTop: 0},
	{magicMagnetPart: 0},
	{wastePoolSpawner: 0},
	{wastePool: 0},
	{wasteBubble: 0},
	{toxicBlob: 0},
	{toxicBlobIcon: 0},
	{toxicBall: 0},
	{toxicExplosion: 0},
	{wasteDrop: 0},
	{reactorCore: 0},
	{entropyKnife: 0},
	{hologram: 0},
	{lazerBase: 0},
	{lazer: 0},
	{Browser: 0},
	{itchBg: 0},
	{meltdownProjectile: 0},
	{meltdownProjectile2: 0},
	{toxicExplosion2: 0},
	{wendigooExt: 0},
	{wendigooBall: 0},
	{runeTower: 0},
	{testy: 0},
	{wendigoSkullExplosion: 0},
	{boneShard: 0},
	{wendigooPuddle: 0},
	{boneShard2: 0},
	{spikeShard: 0},
	{wendigooBall2: 0},
	{import: 0},
	{wall: 0},
	{samuraiSword: 0},
	{swordSlash: 0},
	{trentBall2: 0},
	{return: 0},
	{suriken: 0},
	{waterDroplet: 0},
	{club: 0},
	{spiritAttack: 0},
	{templeSpawner: 0},
	{healSpirit: 0},
	{difficultyController: 0},
	{banner: 0},
	{pyramidRaidSpawn2: 0},
	{lanternFireBig: 0},
	{bombLantern: 0},
	{Fade: 0},
	{bombOrb: 0},
	{dragonRay: 0},
	{nimbus: 0},
	{wukongStaffHitbox: 0},
	{wukongStaff: 0},
	{nimbus2: 0},
	{wukongStaff2: 0},
	{nimbusExplosion: 0},
	{spiritFlame2: 0},
	{electricBall: 0},
	{electricField: 0},
	{oilIcon: 0},
	{oil: 0},
	{oilPuddle: 0},
	{oilBall: 0},
	{hypoBlast: 0},
	{chargeParticle: 0},
	{jellyTentacle: 0},
	{hasShield: 0},
	{electricField2: 0},
	{jellyTentacle2: 0},
	{oilBall2: 0},
	{rockProj: 0},
	{rejuvenationPart: 0},
	{grasspatch: 0},
	{logProj: 0},
	{logProj2: 0},
	{woodlingOrb: 0},
	{linkage: 0},
	{SpriteFont: 0},
	{sporeHeal: 0},
	{magicCircle2: 0},
	{resName: 0},
	{woodlingResGem: 0},
	{slimeIcons: 0},
	{armorPieces: 0},
	{Timer2: 0},
	{meleeWeapons: 0},
	{sort: 0},
	{slots: 0},
	{Resources: 0},
	{playerProjectiles: 0},
	{damagers: 0},
	{collisioners: 0},
	{follow: 0},
	{knockback: 0},
	{enemies: 0},
	{enemyProjectiles: 0},
	{summons: 0},
	{heads: 0},
	{spirits: 0},
	{puddles: 0},
	{yoyoHitboxes: 0},
	{selectedObj: 0},
	{defense: 0},
	{tempDefense: 0},
	{selectedID: 0},
	{selectedName: 0},
	{canUseItem: 0},
	{canPickup: 0},
	{moveID: 0},
	{recipeID: 0},
	{craftingStationID: 0},
	{test: 0},
	{mana: 0},
	{maxMana: 0},
	{manaRegen: 0},
	{manaRegenSpeed: 0},
	{maxHealth: 0},
	{healthRegen: 0},
	{healthRegenSpeed: 0},
	{swapType: 0},
	{daysTime: 0},
	{isBossbattle: 0},
	{bossHealth: 0},
	{bossMaxHealth: 0},
	{lastVisited: 0},
	{summonMaxWeight: 0},
	{hasSave: 0},
	{load: 0},
	{load2: 0},
	{maxManaUnequip: 0},
	{maxHealthUnequip: 0},
	{summonMaxWeightUnequip: 0},
	{waterBreath: 0},
	{saves: 0},
	{commands: 0},
	{bossInt: 0},
	{storedGameState: 0},
	{storedGameGameState: 0},
	{difficulty: 0},
	{bigText: 0},
	{tempID: 0},
	{tempAmount: 0},
	{tempType: 0},
	{meleeDamage: 0},
	{rangedDamage: 0},
	{magicDamage: 0},
	{helmetName: 0},
	{chestplateName: 0},
	{bootsName: 0},
	{Name: 0},
	{isRestart: 0},
	{slotID: 0},
	{amount: 0},
	{effectName: 0},
	{effectDuration: 0},
	{effectPermanent: 0},
	{entranceX: 0},
	{entranceY: 0},
	{entranceID: 0},
	{firstTime: 0},
	{dropID: 0},
	{minimum: 0},
	{maximum: 0},
	{spread: 0},
	{choice: 0},
	{choice2: 0},
	{cryoWormChoice: 0},
	{pick: 0},
	{isPermanent: 0},
	{StorX: 0},
	{StorY: 0},
	{StorUID: 0},
	{tempAmountPickup: 0},
	{itemID: 0},
	{cont: 0},
	{start: 0},
	{recipe: 0},
	{rand: 0},
	{poolX: 0},
	{poolY: 0}
];

self.InstanceType = {
	craftButton: class extends self.ISpriteInstance {},
	craftButton2: class extends self.ISpriteInstance {},
	craftButton3: class extends self.ISpriteInstance {},
	craftingSlot: class extends self.ISpriteInstance {},
	hotbarSlot2: class extends self.ISpriteInstance {},
	inventorySlot: class extends self.ISpriteInstance {},
	inventorys: class extends self.ISpriteInstance {},
	manaBarBack: class extends self.ISpriteInstance {},
	manaBarBack2: class extends self.ISpriteInstance {},
	map: class extends self.ISpriteInstance {},
	placingCursor: class extends self.ISpriteInstance {},
	selectionSlot: class extends self.ISpriteInstance {},
	selector: class extends self.ISpriteInstance {},
	selectorInv: class extends self.ISpriteInstance {},
	testingInventorys: class extends self.ISpriteInstance {},
	manaBar: class extends self.ITiledBackgroundInstance {},
	manaBarBack3: class extends self.ISpriteInstance {},
	healthBar: class extends self.ITiledBackgroundInstance {},
	healthBarBack: class extends self.ISpriteInstance {},
	bossBarBack: class extends self.ISpriteInstance {},
	bossBarFront: class extends self.ISpriteInstance {},
	bossBar: class extends self.ITiledBackgroundInstance {},
	chestSlot: class extends self.ISpriteInstance {},
	ammoVisibility: class extends self.ISpriteInstance {},
	trash: class extends self.ISpriteInstance {},
	offhandVisbility: class extends self.ISpriteInstance {},
	craftMaxButton: class extends self.ISpriteInstance {},
	craftingStations: class extends self.ISpriteInstance {},
	torch: class extends self.ISpriteInstance {},
	torchLight: class extends self.ISpriteInstance {},
	Tree: class extends self.ISpriteInstance {},
	chest: class extends self.ISpriteInstance {},
	caveEnterance: class extends self.ISpriteInstance {},
	craftingStations2: class extends self.ISpriteInstance {},
	torchLight2: class extends self.ISpriteInstance {},
	playerLight: class extends self.ISpriteInstance {},
	Tree2: class extends self.ISpriteInstance {},
	plantLight: class extends self.ISpriteInstance {},
	spark: class extends self.ISpriteInstance {},
	thorn: class extends self.ISpriteInstance {},
	thornBall: class extends self.ISpriteInstance {},
	ankhBall: class extends self.ISpriteInstance {},
	ankhBall2: class extends self.ISpriteInstance {},
	woodenArrow: class extends self.ISpriteInstance {},
	ankhBall3: class extends self.ISpriteInstance {},
	cursedArrow: class extends self.ISpriteInstance {},
	miniSprout: class extends self.ISpriteInstance {},
	ironTippedArrow: class extends self.ISpriteInstance {},
	bolt: class extends self.ISpriteInstance {},
	slimeBull: class extends self.ISpriteInstance {},
	leafBall: class extends self.ISpriteInstance {},
	silverTippedArrow: class extends self.ISpriteInstance {},
	playerIcicle: class extends self.ISpriteInstance {},
	playerIcicle2: class extends self.ISpriteInstance {},
	playerIcicle3: class extends self.ISpriteInstance {},
	cursedHandProjectile: class extends self.ISpriteInstance {},
	cursedBolt: class extends self.ISpriteInstance {},
	leafBall2: class extends self.ISpriteInstance {},
	quake: class extends self.ISpriteInstance {},
	curseExplosion: class extends self.ISpriteInstance {},
	runeShot: class extends self.ISpriteInstance {},
	curseExplosion2: class extends self.ISpriteInstance {},
	spiritSword: class extends self.ISpriteInstance {},
	coin: class extends self.ISpriteInstance {},
	ankhBall4: class extends self.ISpriteInstance {},
	wave: class extends self.ISpriteInstance {},
	coralArrow: class extends self.ISpriteInstance {},
	staticField: class extends self.ISpriteInstance {},
	staticArrow: class extends self.ISpriteInstance {},
	orbitBubble: class extends self.ISpriteInstance {},
	bubble: class extends self.ISpriteInstance {},
	seaFoamBall: class extends self.ISpriteInstance {},
	seafoamPuddle: class extends self.ISpriteInstance {},
	spiritShield: class extends self.ISpriteInstance {},
	toothedShieldHitbox: class extends self.ISpriteInstance {},
	fireTrail: class extends self.ISpriteInstance {},
	playerIcicle4: class extends self.ISpriteInstance {},
	flare: class extends self.ISpriteInstance {},
	fieryArrow: class extends self.ISpriteInstance {},
	miniMeteor: class extends self.ISpriteInstance {},
	yoyoDamage: class extends self.ISpriteInstance {},
	waterbolt: class extends self.ISpriteInstance {},
	typhoon: class extends self.ISpriteInstance {},
	flyingKnife: class extends self.ISpriteInstance {},
	flyArrow: class extends self.ISpriteInstance {},
	grubBull: class extends self.ISpriteInstance {},
	bloodWave: class extends self.ISpriteInstance {},
	miniCocoon: class extends self.ISpriteInstance {},
	grubBullInfestation: class extends self.ISpriteInstance {},
	throwingCocoon: class extends self.ISpriteInstance {},
	grubBull2: class extends self.ISpriteInstance {},
	flyOrbital: class extends self.ISpriteInstance {},
	centipedeOrbital: class extends self.ISpriteInstance {},
	windArrow: class extends self.ISpriteInstance {},
	windArrow2: class extends self.ISpriteInstance {},
	hadesHatchet: class extends self.ISpriteInstance {},
	coin2: class extends self.ISpriteInstance {},
	lavaBullet: class extends self.ISpriteInstance {},
	starShard: class extends self.ISpriteInstance {},
	sakuraBullet: class extends self.ISpriteInstance {},
	petal: class extends self.ISpriteInstance {},
	playerIcicle5: class extends self.ISpriteInstance {},
	windExplosion: class extends self.ISpriteInstance {},
	cherrySplinterSpec: class extends self.ISpriteInstance {},
	cherryShuriken: class extends self.ISpriteInstance {},
	blisterBladeSpecial: class extends self.ISpriteInstance {},
	cherryWave: class extends self.ISpriteInstance {},
	bubbleRingSpawner: class extends self.ISpriteInstance {},
	bulbField: class extends self.ISpriteInstance {},
	centipedeSpawner: class extends self.ISpriteInstance {},
	cherryShurikenSpawner: class extends self.ISpriteInstance {},
	spiritBomb: class extends self.ISpriteInstance {},
	spiritBall: class extends self.ISpriteInstance {},
	spiritBall2: class extends self.ISpriteInstance {},
	soulDagger: class extends self.ISpriteInstance {},
	ghostSpawner: class extends self.ISpriteInstance {},
	ghostOrbital: class extends self.ISpriteInstance {},
	soulWave: class extends self.ISpriteInstance {},
	epitomeSkull: class extends self.ISpriteInstance {},
	soulExplosion: class extends self.ISpriteInstance {},
	soulArrow: class extends self.ISpriteInstance {},
	graveArrow: class extends self.ISpriteInstance {},
	soulBall: class extends self.ISpriteInstance {},
	soulBall2: class extends self.ISpriteInstance {},
	spiritSpearWave: class extends self.ISpriteInstance {},
	spiritSpearWave2: class extends self.ISpriteInstance {},
	graveArrow2: class extends self.ISpriteInstance {},
	hydraSpawner: class extends self.ISpriteInstance {},
	hydraBullet: class extends self.ISpriteInstance {},
	bloodExplosion: class extends self.ISpriteInstance {},
	leafBall3: class extends self.ISpriteInstance {},
	curseExplosion3: class extends self.ISpriteInstance {},
	iceBall: class extends self.ISpriteInstance {},
	iceJavelin: class extends self.ISpriteInstance {},
	frostBowIcicle: class extends self.ISpriteInstance {},
	blizzardZone: class extends self.ISpriteInstance {},
	blizzardBull: class extends self.ISpriteInstance {},
	petal2: class extends self.ISpriteInstance {},
	staticField2: class extends self.ISpriteInstance {},
	radBeam: class extends self.ISpriteInstance {},
	nuclearArrow: class extends self.ISpriteInstance {},
	radiationExplosion: class extends self.ISpriteInstance {},
	radBall: class extends self.ISpriteInstance {},
	radRocket: class extends self.ISpriteInstance {},
	megaRadRocket: class extends self.ISpriteInstance {},
	bloodExplosion2: class extends self.ISpriteInstance {},
	radKnife: class extends self.ISpriteInstance {},
	mutantArrow: class extends self.ISpriteInstance {},
	coin3: class extends self.ISpriteInstance {},
	skeletonHand: class extends self.ISpriteInstance {},
	stagSpike: class extends self.ISpriteInstance {},
	stagSpike2: class extends self.ISpriteInstance {},
	stagSpike3: class extends self.ISpriteInstance {},
	woodenSpinner: class extends self.ISpriteInstance {},
	ironSpinner: class extends self.ISpriteInstance {},
	fierySpinner: class extends self.ISpriteInstance {},
	pumpkin: class extends self.ISpriteInstance {},
	pumpkin2: class extends self.ISpriteInstance {},
	pumpkin3: class extends self.ISpriteInstance {},
	fireWave: class extends self.ISpriteInstance {},
	namiBubble: class extends self.ISpriteInstance {},
	moriLeaf: class extends self.ISpriteInstance {},
	flyingKnife2: class extends self.ISpriteInstance {},
	koriIcicle: class extends self.ISpriteInstance {},
	fireworkArrow: class extends self.ISpriteInstance {},
	fireworkExplosion: class extends self.ISpriteInstance {},
	karmaShot: class extends self.ISpriteInstance {},
	spiritBall3: class extends self.ISpriteInstance {},
	laser: class extends self.ISpriteInstance {},
	knot: class extends self.ISpriteInstance {},
	spiritBall4: class extends self.ISpriteInstance {},
	wukongPetStaff: class extends self.ISpriteInstance {},
	wukongPetStaff2: class extends self.ISpriteInstance {},
	tentacleSpearTyphoon: class extends self.ISpriteInstance {},
	trident: class extends self.ISpriteInstance {},
	squidJaveline: class extends self.ISpriteInstance {},
	torrentBlast: class extends self.ISpriteInstance {},
	torrentMegaBlast: class extends self.ISpriteInstance {},
	shellArrow: class extends self.ISpriteInstance {},
	jellyBall: class extends self.ISpriteInstance {},
	staticField3: class extends self.ISpriteInstance {},
	jellyShock: class extends self.ISpriteInstance {},
	hollowCore: class extends self.ISpriteInstance {},
	hollowBall: class extends self.ISpriteInstance {},
	megaHollowCore: class extends self.ISpriteInstance {},
	chasmCrusherBull: class extends self.ISpriteInstance {},
	starfish: class extends self.ISpriteInstance {},
	starfishSpawner: class extends self.ISpriteInstance {},
	spiritWhale: class extends self.ISpriteInstance {},
	spiritFish: class extends self.ISpriteInstance {},
	axe: class extends self.ISpriteInstance {},
	dagger: class extends self.ISpriteInstance {},
	pickaxe: class extends self.ISpriteInstance {},
	shovel: class extends self.ISpriteInstance {},
	sword: class extends self.ISpriteInstance {},
	wand: class extends self.ISpriteInstance {},
	bow: class extends self.ISpriteInstance {},
	woodChip: class extends self.ISpriteInstance {},
	cryolite: class extends self.ISpriteInstance {},
	anubisGuardianSpirit: class extends self.ISpriteInstance {},
	tome: class extends self.ISpriteInstance {},
	tome2: class extends self.ISpriteInstance {},
	jellyPet: class extends self.ISpriteInstance {},
	sunSpot: class extends self.ISpriteInstance {},
	windSpirit: class extends self.ISpriteInstance {},
	curseFlameSpawner: class extends self.ISpriteInstance {},
	zombiePet: class extends self.ISpriteInstance {},
	deathClawSpec: class extends self.ISpriteInstance {},
	quark: class extends self.ISpriteInstance {},
	bow2: class extends self.ISpriteInstance {},
	vampireBat: class extends self.ISpriteInstance {},
	boomerang: class extends self.ISpriteInstance {},
	boomerang2: class extends self.ISpriteInstance {},
	wukongPet: class extends self.ISpriteInstance {},
	damage: class extends self.ISpriteFontInstance {},
	defenseCounter: class extends self.ISpriteFontInstance {},
	description: class extends self.ISpriteFontInstance {},
	islandName: class extends self.ISpriteFontInstance {},
	label: class extends self.ISpriteFontInstance {},
	label2: class extends self.ISpriteFontInstance {},
	manaCounter: class extends self.ISpriteFontInstance {},
	label4: class extends self.ISpriteFontInstance {},
	selectionName: class extends self.ISpriteFontInstance {},
	healthCounter: class extends self.ISpriteFontInstance {},
	bossHealthCounter: class extends self.ISpriteFontInstance {},
	message: class extends self.ISpriteFontInstance {},
	label5: class extends self.ISpriteFontInstance {},
	difficultyText: class extends self.ISpriteFontInstance {},
	phaseReader: class extends self.ISpriteFontInstance {},
	staticLabel: class extends self.ISpriteFontInstance {},
	dropItem: class extends self.ISpriteInstance {},
	hammer: class extends self.ISpriteInstance {},
	enemiesSpawnerSpawner: class extends self.ISpriteInstance {},
	helmet: class extends self.ISpriteInstance {},
	island: class extends self.ITilemapInstance {},
	islandSprites: class extends self.ISpriteInstance {},
	islandSprites2: class extends self.ISpriteInstance {},
	itemIcon: class extends self.ISpriteInstance {},
	player2: class extends self.ISpriteInstance {},
	player3: class extends self.ISpriteInstance {},
	playerHitbox: class extends self.ISpriteInstance {},
	shadow: class extends self.ISpriteInstance {},
	spawner: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	trueEnemySpawner: class extends self.ISpriteInstance {},
	water: class extends self.ITiledBackgroundInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	TiledBackground7: class extends self.ITiledBackgroundInstance {},
	TiledBackground8: class extends self.ITiledBackgroundInstance {},
	TiledBackground9: class extends self.ITiledBackgroundInstance {},
	water2: class extends self.ITiledBackgroundInstance {},
	meteorShadow: class extends self.ISpriteInstance {},
	yoyo: class extends self.ISpriteInstance {},
	TiledBackground10: class extends self.ITiledBackgroundInstance {},
	TiledBackground11: class extends self.ITiledBackgroundInstance {},
	arrowShadow: class extends self.ISpriteInstance {},
	TiledBackground12: class extends self.ITiledBackgroundInstance {},
	Audio: class extends self.IInstance {},
	bloodSlimeCrack: class extends self.ISpriteInstance {},
	boat: class extends self.ISpriteInstance {},
	buffIcon: class extends self.ISpriteInstance {},
	cherryGuardianCrack: class extends self.ISpriteInstance {},
	Clipboard: class extends self.IInstance {},
	clouds: class extends self.IWorldInstance {},
	clouds2: class extends self.IWorldInstance {},
	darkness: class extends self.ISpriteInstance {},
	deathText: class extends self.ISpriteInstance {},
	deathText2: class extends self.ISpriteInstance {},
	drowning: class extends self.ISpriteInstance {},
	TiledBackground13: class extends self.ITiledBackgroundInstance {},
	skeletonKingCrack: class extends self.ISpriteInstance {},
	bubbles: class extends self.IParticlesInstance {},
	effect: class extends self.ISpriteInstance {},
	effectController: class extends self.ISpriteInstance {},
	fieryTotem: class extends self.ISpriteInstance {},
	flyingKnifeSpawner: class extends self.ISpriteInstance {},
	goldRingSpawner: class extends self.ISpriteInstance {},
	goToEnterace: class extends self.ISpriteInstance {},
	hadesCrack: class extends self.ISpriteInstance {},
	HadesShield: class extends self.ISpriteInstance {},
	healingBlossom: class extends self.ISpriteInstance {},
	healingCircle: class extends self.ISpriteInstance {},
	healingCircle2: class extends self.ISpriteInstance {},
	healTotem: class extends self.ISpriteInstance {},
	icicle: class extends self.ISpriteInstance {},
	icicleShower: class extends self.ISpriteInstance {},
	importSave: class extends self.ISpriteInstance {},
	TiledBackground14: class extends self.ITiledBackgroundInstance {},
	icicle4: class extends self.ISpriteInstance {},
	icicleBackBurn: class extends self.ISpriteInstance {},
	icicleShower2: class extends self.ISpriteInstance {},
	borealCrack: class extends self.ISpriteInstance {},
	water3: class extends self.ITiledBackgroundInstance {},
	TiledBackground15: class extends self.ITiledBackgroundInstance {},
	discordLink: class extends self.ISpriteInstance {},
	radRocketShot: class extends self.ISpriteInstance {},
	radKnifeSpawner: class extends self.ISpriteInstance {},
	importSave2: class extends self.ISpriteInstance {},
	meltdownCrack: class extends self.ISpriteInstance {},
	stagStaff: class extends self.ISpriteInstance {},
	wendigooCrack: class extends self.ISpriteInstance {},
	TiledBackground16: class extends self.ITiledBackgroundInstance {},
	candleFireSpawner: class extends self.ISpriteInstance {},
	dragonCrack: class extends self.ISpriteInstance {},
	boomerangBase: class extends self.ISpriteInstance {},
	wukongCrack: class extends self.ISpriteInstance {},
	LanternLordCrack: class extends self.ISpriteInstance {},
	healingCircle3: class extends self.ISpriteInstance {},
	TiledBackground17: class extends self.ITiledBackgroundInstance {},
	tridentVortexSpawner: class extends self.ISpriteInstance {},
	waveSpawner: class extends self.ISpriteInstance {},
	amalgamationCrack: class extends self.ISpriteInstance {},
	TiledBackground18: class extends self.ITiledBackgroundInstance {},
	mummy: class extends self.ISpriteInstance {},
	desertNado: class extends self.ISpriteInstance {},
	pharaoh: class extends self.ISpriteInstance {},
	mummy2: class extends self.ISpriteInstance {},
	cursedMummy: class extends self.ISpriteInstance {},
	trent: class extends self.ISpriteInstance {},
	slime: class extends self.ISpriteInstance {},
	woodling: class extends self.ISpriteInstance {},
	cerebulbum: class extends self.ISpriteInstance {},
	bulb: class extends self.ISpriteInstance {},
	spider: class extends self.ISpriteInstance {},
	worm: class extends self.ISpriteInstance {},
	pig: class extends self.ISpriteInstance {},
	woodlingWizard: class extends self.ISpriteInstance {},
	bulb2: class extends self.ISpriteInstance {},
	frostSlime: class extends self.ISpriteInstance {},
	icicleConstruct: class extends self.ISpriteInstance {},
	cryoWormHead: class extends self.ISpriteInstance {},
	cryoWormBody: class extends self.ISpriteInstance {},
	icePickHead: class extends self.ISpriteInstance {},
	icePickBody: class extends self.ISpriteInstance {},
	cursedMummy2: class extends self.ISpriteInstance {},
	cursedMummy3: class extends self.ISpriteInstance {},
	cursedSkull: class extends self.ISpriteInstance {},
	fish: class extends self.ISpriteInstance {},
	piranha: class extends self.ISpriteInstance {},
	puffer: class extends self.ISpriteInstance {},
	jellyFish: class extends self.ISpriteInstance {},
	megaJelly: class extends self.ISpriteInstance {},
	lavaSpire: class extends self.ISpriteInstance {},
	emberling: class extends self.ISpriteInstance {},
	redWizard: class extends self.ISpriteInstance {},
	magmaKnight: class extends self.ISpriteInstance {},
	grub: class extends self.ISpriteInstance {},
	cocoon: class extends self.ISpriteInstance {},
	fly: class extends self.ISpriteInstance {},
	centipedeHead: class extends self.ISpriteInstance {},
	centipedeBody: class extends self.ISpriteInstance {},
	bloodSlime: class extends self.ISpriteInstance {},
	maggotHead: class extends self.ISpriteInstance {},
	maggotBody: class extends self.ISpriteInstance {},
	marbleWarrior: class extends self.ISpriteInstance {},
	marbleArcher: class extends self.ISpriteInstance {},
	philosopher: class extends self.ISpriteInstance {},
	monolith: class extends self.ISpriteInstance {},
	grandMarbleWarrior: class extends self.ISpriteInstance {},
	monoSlime: class extends self.ISpriteInstance {},
	monoSlime2: class extends self.ISpriteInstance {},
	hades: class extends self.ISpriteInstance {},
	quetzalcoatlHead: class extends self.ISpriteInstance {},
	quetzalcoatlBody: class extends self.ISpriteInstance {},
	enchantedSlime: class extends self.ISpriteInstance {},
	stoneConstruct: class extends self.ISpriteInstance {},
	cherryWoodling: class extends self.ISpriteInstance {},
	cherryTrent: class extends self.ISpriteInstance {},
	cherryGuardian: class extends self.ISpriteInstance {},
	ghoul: class extends self.ISpriteInstance {},
	frankenstein: class extends self.ISpriteInstance {},
	ghost: class extends self.ISpriteInstance {},
	skeleton: class extends self.ISpriteInstance {},
	skeletonLegs: class extends self.ISpriteInstance {},
	skeleton2: class extends self.ISpriteInstance {},
	trainingDummy: class extends self.ISpriteInstance {},
	weaver: class extends self.ISpriteInstance {},
	monolith2: class extends self.ISpriteInstance {},
	skeletonKing: class extends self.ISpriteInstance {},
	enchantedSlimeExt: class extends self.ISpriteInstance {},
	frostedSlime: class extends self.ISpriteInstance {},
	blizzard: class extends self.ISpriteInstance {},
	permafrostPickHead: class extends self.ISpriteInstance {},
	permafrostPickBody: class extends self.ISpriteInstance {},
	boreal: class extends self.ISpriteInstance {},
	toxicGhoul: class extends self.ISpriteInstance {},
	wasteCrab: class extends self.ISpriteInstance {},
	nuclearWormHead: class extends self.ISpriteInstance {},
	nuclearWormBody: class extends self.ISpriteInstance {},
	nuclearConstruct: class extends self.ISpriteInstance {},
	meltdown: class extends self.ISpriteInstance {},
	wendigoo: class extends self.ISpriteInstance {},
	wendigoBrute: class extends self.ISpriteInstance {},
	wendigoSentry: class extends self.ISpriteInstance {},
	mummy3: class extends self.ISpriteInstance {},
	samurai: class extends self.ISpriteInstance {},
	lantern: class extends self.ISpriteInstance {},
	ninja: class extends self.ISpriteInstance {},
	umbrella: class extends self.ISpriteInstance {},
	cyclops: class extends self.ISpriteInstance {},
	spirit: class extends self.ISpriteInstance {},
	lanternLord: class extends self.ISpriteInstance {},
	dragon: class extends self.ISpriteInstance {},
	dragonBody: class extends self.ISpriteInstance {},
	wukong: class extends self.ISpriteInstance {},
	glowJelly: class extends self.ISpriteInstance {},
	barnacle: class extends self.ISpriteInstance {},
	eelHead: class extends self.ISpriteInstance {},
	eelBody: class extends self.ISpriteInstance {},
	amalgamation: class extends self.ISpriteInstance {},
	leviathanHead: class extends self.ISpriteInstance {},
	leviathanBody: class extends self.ISpriteInstance {},
	woodling2: class extends self.ISpriteInstance {},
	ancientWoodlingDrone: class extends self.ISpriteInstance {},
	ancientWoodling: class extends self.ISpriteInstance {},
	puffBat: class extends self.ISpriteInstance {},
	ancientWoodlingPriest: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	CraftingData: class extends self.IArrayInstance {},
	inventory: class extends self.IArrayInstance {},
	itemData: class extends self.IArrayInstance {},
	tableData: class extends self.IArrayInstance {},
	chestStorage: class extends self.IArrayInstance {},
	islandData: class extends self.IArrayInstance {},
	effectArray: class extends self.IArrayInstance {},
	effects: class extends self.IListInstance {},
	FileChooser: class extends self.IWorldInstance {},
	FileSystem: class extends self.IInstance {},
	gameState: class extends self.IArrayInstance {},
	_9patch: class extends self.IWorldInstance {},
	bigBloodBall: class extends self.ISpriteInstance {},
	cherryRip: class extends self.ISpriteInstance {},
	cerebulbumCrack: class extends self.ISpriteInstance {},
	cherrySuriken: class extends self.ISpriteInstance {},
	cherrySuriken2: class extends self.ISpriteInstance {},
	coatlPortal: class extends self.ISpriteInstance {},
	cryoball: class extends self.ISpriteInstance {},
	cryoCore: class extends self.ISpriteInstance {},
	cryoWormCrack: class extends self.ISpriteInstance {},
	cursedSoul: class extends self.ISpriteInstance {},
	dockingPoint: class extends self.ISpriteInstance {},
	bone: class extends self.ISpriteInstance {},
	emberBall: class extends self.ISpriteInstance {},
	frostSlimeExt: class extends self.ISpriteInstance {},
	ghostBall: class extends self.ISpriteInstance {},
	gooBall: class extends self.ISpriteInstance {},
	gooSpawn: class extends self.ISpriteInstance {},
	gooSpawn2: class extends self.ISpriteInstance {},
	hadesFireball: class extends self.ISpriteInstance {},
	hadesFireball2: class extends self.ISpriteInstance {},
	hadesFireball3: class extends self.ISpriteInstance {},
	hadesFireball4: class extends self.ISpriteInstance {},
	hadesFireball5: class extends self.ISpriteInstance {},
	icicle2: class extends self.ISpriteInstance {},
	icicle3: class extends self.ISpriteInstance {},
	frostedSlimeExt: class extends self.ISpriteInstance {},
	lanternFire: class extends self.ISpriteInstance {},
	lanternFire2: class extends self.ISpriteInstance {},
	lanternFire3: class extends self.ISpriteInstance {},
	lanternFire4: class extends self.ISpriteInstance {},
	jadeWukong: class extends self.ISpriteInstance {},
	slimeBall: class extends self.ISpriteInstance {},
	slimeBall2: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	sandball: class extends self.ISpriteInstance {},
	pharoahBall: class extends self.ISpriteInstance {},
	pharaohCoffin: class extends self.ISpriteInstance {},
	shine: class extends self.ISpriteInstance {},
	progress: class extends self.ISpriteInstance {},
	trentBall: class extends self.ISpriteInstance {},
	vinePoker: class extends self.ISpriteInstance {},
	slimeExt: class extends self.ISpriteInstance {},
	trashEmpty: class extends self.ISpriteInstance {},
	vineSpawner: class extends self.ISpriteInstance {},
	vineSpawner2: class extends self.ISpriteInstance {},
	miniBulb: class extends self.ISpriteInstance {},
	slimeShot: class extends self.ISpriteInstance {},
	returnDisabled: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	saveIcon: class extends self.ISpriteInstance {},
	saveButton: class extends self.ISpriteInstance {},
	magicCircle: class extends self.ISpriteInstance {},
	waveGleam: class extends self.ITiledBackgroundInstance {},
	totem: class extends self.ISpriteInstance {},
	pyramidRaidSpawn: class extends self.ISpriteInstance {},
	sandball2: class extends self.ISpriteInstance {},
	shop: class extends self.ISpriteInstance {},
	mapDottedLine: class extends self.ITiledBackgroundInstance {},
	timerReload: class extends self.ISpriteInstance {},
	sandball3: class extends self.ISpriteInstance {},
	shock: class extends self.ISpriteInstance {},
	lightning: class extends self.ISpriteInstance {},
	pharoahBall2: class extends self.ISpriteInstance {},
	jellyCrack: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	spawnRegion: class extends self.ISpriteInstance {},
	lavaPool: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	lavaPoolSpawner: class extends self.ISpriteInstance {},
	magmaBomb: class extends self.ISpriteInstance {},
	lavaPool2: class extends self.ISpriteInstance {},
	meteorSpawner: class extends self.ISpriteInstance {},
	magmaBomb2: class extends self.ISpriteInstance {},
	meteor: class extends self.ISpriteInstance {},
	meteorBull: class extends self.ISpriteInstance {},
	meteorSpawner2: class extends self.ISpriteInstance {},
	magmaBomb3: class extends self.ISpriteInstance {},
	meteor2: class extends self.ISpriteInstance {},
	magmaKnightCrack: class extends self.ISpriteInstance {},
	meteorShower: class extends self.ISpriteInstance {},
	string: class extends self.ITiledBackgroundInstance {},
	specialProgress: class extends self.ISpriteInstance {},
	spitball: class extends self.ISpriteInstance {},
	slimeExt2: class extends self.ISpriteInstance {},
	smallBloodBall: class extends self.ISpriteInstance {},
	marbleField: class extends self.IWorldInstance {},
	marbleFieldSpawner: class extends self.ISpriteInstance {},
	marbleFieldHitbox: class extends self.ISpriteInstance {},
	sandball4: class extends self.ISpriteInstance {},
	marbleBow: class extends self.ISpriteInstance {},
	marbleArcherArrow: class extends self.ISpriteInstance {},
	philosopherRocketIcon: class extends self.ISpriteInstance {},
	philosopherRocket: class extends self.ISpriteInstance {},
	magmaBomb4: class extends self.ISpriteInstance {},
	missleRain: class extends self.ISpriteInstance {},
	sandball5: class extends self.ISpriteInstance {},
	slimeExt3: class extends self.ISpriteInstance {},
	slimeExt4: class extends self.ISpriteInstance {},
	meteor3: class extends self.ISpriteInstance {},
	meteorSpawner3: class extends self.ISpriteInstance {},
	infernoRingSpawner: class extends self.ISpriteInstance {},
	quetzalCoatlCrack: class extends self.ISpriteInstance {},
	monolithCrack: class extends self.ISpriteInstance {},
	teleportBeam: class extends self.ISpriteInstance {},
	starBit: class extends self.ISpriteInstance {},
	mossOrbital: class extends self.ISpriteInstance {},
	magmaBomb5: class extends self.ISpriteInstance {},
	meteorSpawner4: class extends self.ISpriteInstance {},
	sakuraExplosionSpawner: class extends self.ISpriteInstance {},
	spiritFlame: class extends self.ISpriteInstance {},
	JSON: class extends self.IJSONInstance {},
	sakuraSpearEffect: class extends self.ISpriteInstance {},
	frankConnection: class extends self.ITiledBackgroundInstance {},
	soul: class extends self.ISpriteInstance {},
	webBall: class extends self.ISpriteInstance {},
	skeletonKingSword: class extends self.ISpriteInstance {},
	skeletonKingSword2: class extends self.ISpriteInstance {},
	skeletonKingFireball: class extends self.ISpriteInstance {},
	skeletonKingFireball2: class extends self.ISpriteInstance {},
	soulBow: class extends self.ISpriteInstance {},
	arrayImportLoadFixer: class extends self.ISpriteInstance {},
	arrayExportLoadFixer: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	newGameConfirm: class extends self.ISpriteInstance {},
	console: class extends self.ITextInputInstance {},
	console2: class extends self.ITextInputInstance {},
	spiritSteelField: class extends self.ISpriteInstance {},
	icePatch: class extends self.ITiledBackgroundInstance {},
	freezeRadius: class extends self.ISpriteInstance {},
	iceFieldSpawner: class extends self.ISpriteInstance {},
	skeletonKingFireball3: class extends self.ISpriteInstance {},
	icicleStar: class extends self.ISpriteInstance {},
	borealBack: class extends self.ISpriteInstance {},
	borealEye: class extends self.ISpriteInstance {},
	megaIcicle: class extends self.ISpriteInstance {},
	megaIcicle2: class extends self.ISpriteInstance {},
	iceRealm: class extends self.ISpriteInstance {},
	iceEye: class extends self.ISpriteInstance {},
	fireflies: class extends self.IParticlesInstance {},
	icePatchBottom: class extends self.IWorldInstance {},
	icePatchTop: class extends self.IWorldInstance {},
	magicMagnetPart: class extends self.ISpriteInstance {},
	wastePoolSpawner: class extends self.ISpriteInstance {},
	wastePool: class extends self.ISpriteInstance {},
	wasteBubble: class extends self.ISpriteInstance {},
	toxicBlob: class extends self.ISpriteInstance {},
	toxicBlobIcon: class extends self.ISpriteInstance {},
	toxicBall: class extends self.ISpriteInstance {},
	toxicExplosion: class extends self.ISpriteInstance {},
	wasteDrop: class extends self.ISpriteInstance {},
	reactorCore: class extends self.ISpriteInstance {},
	entropyKnife: class extends self.ISpriteInstance {},
	hologram: class extends self.ISpriteInstance {},
	lazerBase: class extends self.ISpriteInstance {},
	lazer: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	itchBg: class extends self.ISpriteInstance {},
	meltdownProjectile: class extends self.ISpriteInstance {},
	meltdownProjectile2: class extends self.ISpriteInstance {},
	toxicExplosion2: class extends self.ISpriteInstance {},
	wendigooExt: class extends self.ISpriteInstance {},
	wendigooBall: class extends self.ISpriteInstance {},
	runeTower: class extends self.ISpriteInstance {},
	testy: class extends self.ISpriteInstance {},
	wendigoSkullExplosion: class extends self.ISpriteInstance {},
	boneShard: class extends self.ISpriteInstance {},
	wendigooPuddle: class extends self.ISpriteInstance {},
	boneShard2: class extends self.ISpriteInstance {},
	spikeShard: class extends self.ISpriteInstance {},
	wendigooBall2: class extends self.ISpriteInstance {},
	import: class extends self.ITextInputInstance {},
	wall: class extends self.ITiledBackgroundInstance {},
	samuraiSword: class extends self.ISpriteInstance {},
	swordSlash: class extends self.ISpriteInstance {},
	trentBall2: class extends self.ISpriteInstance {},
	suriken: class extends self.ISpriteInstance {},
	waterDroplet: class extends self.ISpriteInstance {},
	club: class extends self.ISpriteInstance {},
	spiritAttack: class extends self.ISpriteInstance {},
	templeSpawner: class extends self.ISpriteInstance {},
	healSpirit: class extends self.ISpriteInstance {},
	difficultyController: class extends self.ISpriteInstance {},
	banner: class extends self.ISpriteInstance {},
	pyramidRaidSpawn2: class extends self.ISpriteInstance {},
	lanternFireBig: class extends self.ISpriteInstance {},
	bombLantern: class extends self.ISpriteInstance {},
	bombOrb: class extends self.ISpriteInstance {},
	dragonRay: class extends self.ISpriteInstance {},
	nimbus: class extends self.ISpriteInstance {},
	wukongStaffHitbox: class extends self.ISpriteInstance {},
	wukongStaff: class extends self.IWorldInstance {},
	nimbus2: class extends self.ISpriteInstance {},
	wukongStaff2: class extends self.IWorldInstance {},
	nimbusExplosion: class extends self.ISpriteInstance {},
	spiritFlame2: class extends self.ISpriteInstance {},
	electricBall: class extends self.ISpriteInstance {},
	electricField: class extends self.ISpriteInstance {},
	oilIcon: class extends self.ISpriteInstance {},
	oil: class extends self.ISpriteInstance {},
	oilPuddle: class extends self.ISpriteInstance {},
	oilBall: class extends self.ISpriteInstance {},
	hypoBlast: class extends self.ISpriteInstance {},
	chargeParticle: class extends self.ISpriteInstance {},
	jellyTentacle: class extends self.ISpriteInstance {},
	electricField2: class extends self.ISpriteInstance {},
	jellyTentacle2: class extends self.ISpriteInstance {},
	oilBall2: class extends self.ISpriteInstance {},
	rockProj: class extends self.ISpriteInstance {},
	rejuvenationPart: class extends self.ISpriteInstance {},
	grasspatch: class extends self.IWorldInstance {},
	logProj: class extends self.ISpriteInstance {},
	logProj2: class extends self.ISpriteInstance {},
	woodlingOrb: class extends self.ISpriteInstance {},
	linkage: class extends self.ITiledBackgroundInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	sporeHeal: class extends self.ISpriteInstance {},
	magicCircle2: class extends self.ISpriteInstance {},
	woodlingResGem: class extends self.ISpriteInstance {},
	slimeIcons: class extends self.ISpriteInstance {},
	armorPieces: class extends self.ISpriteInstance {},
	meleeWeapons: class extends self.ISpriteInstance {},
	sort: class extends self.ISpriteInstance {},
	slots: class extends self.ISpriteInstance {},
	Resources: class extends self.ISpriteInstance {},
	playerProjectiles: class extends self.ISpriteInstance {},
	damagers: class extends self.ISpriteInstance {},
	collisioners: class extends self.ISpriteInstance {},
	enemies: class extends self.ISpriteInstance {},
	enemyProjectiles: class extends self.ISpriteInstance {},
	summons: class extends self.ISpriteInstance {},
	heads: class extends self.ISpriteInstance {},
	spirits: class extends self.ISpriteInstance {},
	puddles: class extends self.ISpriteInstance {},
	yoyoHitboxes: class extends self.ISpriteInstance {}
}